---
 - name: delete if the file is executable
   hosts: all
   tasks: 
     - name: compute info about the file
       stat: 
         path: /tmp/file1
       register: b
     - name: display the output os the above module
       debug: 
          var: b
     - name: delete if the file is executable
       file: 
         name: /tmp/file1
         state: absent
       when: b.stat.executable == true
...         
         


