---
 - name: implementing host scope variables
   hosts: 172.31.26.60
   tasks: 
      - name: create user
        user:
           name: "{{a}}"
           password: "{{b}}"
           uid: "{{c}}"
           home: "{{d}}"
           comment: "{{e}}"
           shell: "{{f}}"
...             
