---
 - name: implementing loops
   hosts: all
   tasks:  
      - name: install s/w app's
        apt: 
          name: "{{item}}"
          state: present
          update_cache: yes
        with_items: 
          - openjdk-17-jdk
          - maven
          - tree
...

