---
 - name: check if f1 file is present if not create f1 folder
   hosts: all
   tasks: 
      - name: check for f1 file1
        stat: 
           path: /home/ubuntu/f1
        register: a
      - name: display output of the above module
        debug:
           var: a
      - name: create f1 folder if f1 file is not prsent
        file: 
           name: /home/ubuntu/f1
           state: directory
        when: a.stat.exists == false     
...
