---
 - name: Install git and clone a remote git repo from github
   hosts: all
   tasks: 
     - name: install git
       apt: 
         name: git
         state: present
         update_cache: yes
     - name:  clone a remote git repo
       git: 
         repo: https://github.com/Aidhaalekhya-1999/maven.git
         dest: /tmp/mygit
...

