---
 - name: configure tomcat using loops
   hosts: all
   tasks: 
      - name: install tomcat10 and tomcat10-admin
        apt: 
          name: "{{item.a}}"
          state: "{{item.b}}"
          update_cache: "{{item.c}}"
        with_items: 
          - {a: tomcat10,b: present,c: yes}
          - {a: tomcat10-admin,b: present,c: no}
      - name: copy them customised tomcat-users.xml file
        copy: 
          src: tomcat-users.xml
          dest: /etc/tomcat10
      - name: change tomcat port from 8080 to 9090
        replace:
            regexp: 8080
            replace: 9090
            path: /etc/tomcat10/server.xml
      - name: restart tomcat
        service:
           name: tomcat10
           state: restarted
      - name: pause for 30 seconds
        pause: 
           seconds: 30

      - name: check on all servers
        uri:
          url: http://172.31.25.111:9090
          status_code: 200
        with_items:
          - http://172.31.25.111:9090
          - http://172.31.24.21:9090
     
        
          
...               
